apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tic-tac-toe-ingress
  namespace: argocd
spec:
  ingressClassName: nginx  # ✅ Use this instead of annotation
  rules:
    - host: tic-tac-toe.punvlmdl01.dsone.3ds.com  # ✅ Use your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tic-tac-toe
                port:
                  number: 80
    - host: argocd.punvlmdl01.dsone.3ds.com  # ✅ Use your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server                
                port:
                  number: 80
