apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tic-tac-toe-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: tic-tac-toe.punvlmdl01.dsone.3ds.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tic-tac-toe
                port:
                  number: 80
    - host: argocd.punvlmdl01.dsone.3ds.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: default  # ✅ Creating a new service in "default"
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local  # ✅ Reference argocd-server in argocd namespace
  ports:
    - port: 80
      targetPort: 80

  name: tic-tac-toe-ingress
  namespace: default
spec:
  ingressClassName: nginx  # ✅ Use this instead of annotation
  rules:
    - host: tic-tac-toe.punvlmdl01.dsone.3ds.com  # ✅ Use your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tic-tac-toe
                port:
                  number: 80
    - host: argocd.punvlmdl01.dsone.3ds.com  # ✅ Use your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server                
                port:
                  number: 80
